version: '3.4'

services:
  db:
    image: "postgres:9.6.2-alpine"
    environment:
      - POSTGRES_USER=infrastructure
      - POSTGRES_PASSWORD=infrastructure
      - POSTGRES_MULTIPLE_DATABASES="infrastructure-test"
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./create_multi_dbs.sh:/docker-entrypoint-initdb.d/create_multi_dbs.sh
      - db-pgdata:/var/lib/postgresql/data
      - ../../tmp/dbdumps:/dbdumps
    ports:
      - "5432:5432"
    networks:
      - backoffice

volumes:
  db-pgdata:

networks:
  backoffice:
